### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by anbraten** [geprog/gringotts#47]
- [x] subscription
  - [x] start subscription
  - [x] change subscription in middle of period (prorations)
  - [x] terminate subscription
  - [x] pause subscription
  - [x] charge customer at end of subscription period
  - [x] skip invoice generation if subscription had 0 amount
  - [ ] charge customer at start of subscription period
  - [ ] get subscription costs forecast
  - [ ] skip subscription change if equal to currently active
- [ ] add plans
  - [ ] use billable aggregation functions
  - [x] configurable payment interval
    - [x] 1 month
    - [ ] 1 week
    - [ ] quarterly
    - [ ] yearly
- [x] invoices
  - [x] for subscriptions
  - [ ] themes for invoices
- [ ] charge customer one-time fee
- [ ] allow customers to charge other customers
- [x] customers
  - [x] manage
  - [x] allow to set language
  - [x] notify customer about
    - [x] new invoices
    - [x] upcoming payment
- [x] payment providers
  - [x] mollie
  - [ ] stripe
- [x] SAAS interface
  - [x] authentication for SAAS backends via api
  - [x] notify SAAS backend about subscription updates
- [x] typescript api client => `@geprog/gringotts-client`
- [x] customer payment methods
  - [x] add payment method
  - [x] verify payment method
- [ ] allow to set payment as paid for mocked provider

# UI

- [x] customers
  - [x] details
  - [ ] update (with balance)
  - [x] change active payment-method
  - [ ] create
- [x] subscriptions
  - [x] details
  - [x] remove error
  - [x] update status
  - [x] show current period date
  - [x] show start
  - [ ] show upcoming invoice price & items
  - [x] terminate
- [x] invoices
  - [x] download
  - [x] details
  - [ ] create new draft
  - [ ] CRUD items of draft invoices
  - [x] charge if not pending yet
  - [ ] allow to reschedule / re-charge failed invoices
- [x] payments
  - [x] details
  - [ ] update state => and thereby update the invoice & subscription
- [x] payment methods
  - [x] details
  - [x] add new payment method
  - [x] remove payment method
- [x] project
  - [x] details
  - [x] invoice data details
  - [ ] update
  - [ ] create
- [ ] auth
  - [ ] login with user
  - [ ] grant user access to project
  - [ ] add / remove from project
  - [ ] register new user
